cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: true

  # Enable Neovim syntax
  env:
    neovim: true

policies:
  ProhibitAutocmdWithNoGroup
	enabled = true
  ProhibitUnecessaryDoubleQuote
	enabled = true
  ProhibitUnusedVariable
	enabled = true
  ProhibitUsingUndeclaredVariable
	enabled = true
