local km = vim.keymap
local dap = require("dap")
km.set({ "n" }, "<F5>", dap.continue)
km.set({ "n" }, "<F10>", dap.step_over)
km.set({ "n" }, "<F11>", dap.step_into)
km.set({ "n" }, "<F12>", dap.step_out)
km.set({ "n" }, "<Leader>b", dap.toggle_breakpoint)
km.set({ "n" }, "<Leader>B", function()
    dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end)
km.set({ "n" }, "<Leader>lp", function()
    dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end)
km.set({ "n" }, "<Leader>dr", dap.repl.open)
km.set({ "n" }, "<Leader>dl", dap.run_last)
