local km = vim.keymap
local dap = require("dap")
km.set({ "n" }, "<F5>", dap.continue)
km.set({ "n" }, "<F10>", dap.step_over)
km.set({ "n" }, "<F11>", dap.step_into)
km.set({ "n" }, "<F12>", dap.step_out)
km.set({ "n" }, "<Leader>b", dap.toggle_breakpoint)
km.set({ "n" }, "<Leader>B", function()
    dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end)
km.set({ "n" }, "<Leader>lp", function()
    dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end)
km.set({ "n" }, "<Leader>dr", dap.repl.open)
km.set({ "n" }, "<Leader>dl", dap.run_last)
-- -- DAP
-- https://www.reddit.com/r/neovim/comments/17h4lt0/how_do_you_debug_code_effectively_if_you_use_vim/
-- keymap("n", "<leader>db", "<cmd>lua require'dap'.toggle_breakpoint()<cr>", opts)
-- keymap("n", "<Leader>dbc", "<cmd>lua require('dap').set_breakpoint(vim.fn.input('Breakpoint condition: '))<cr>")
-- keymap("n", "<leader>dc", "<cmd>lua require'dap'.continue()<cr>", opts)
-- keymap("n", "<leader>di", "<cmd>lua require'dap'.step_into()<cr>", opts)
-- keymap("n", "<leader>do", "<cmd>lua require'dap'.step_over()<cr>", opts)
-- keymap("n", "<leader>dO", "<cmd>lua require'dap'.step_out()<cr>", opts)
-- keymap("n", "<leader>dr", "<cmd>lua require'dap'.repl.toggle()<cr>", opts)
-- keymap("n", "<leader>dl", "<cmd>lua require'dap'.run_last()<cr>", opts)
-- keymap("n", "<leader>du", "<cmd>lua require'dapui'.toggle()<cr>", opts)
-- keymap("n", "<leader>dt", "<cmd>lua require'dap'.terminate()<cr>", opts)
